[package]
name = "jojom/gamebase"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
fusion = "elttob/fusion@0.3.0"

[server-dependencies]
ProfileStore = "lm-loleris/profilestore@1.0.3"